---
apiVersion: ark.ulagbulag.io/v1alpha1
kind: Widget
metadata:
  name: optimize_graph
  labels:
    dash.ulagbulag.io/page: analyze
    dash.ulagbulag.io/title: Graph Optimizer
spec:
  actions:
    - name: dataset
      kind: DatasetRead
      spec:
        type: Graph

    - name: dataset_visualize
      kind: DatasetVisualize
      spec:
        key: /dataset/value

    - name: optimized_dataset
      kind: DatasetOptimize
      metadata:
        column: New
      spec:
        key: /dataset/value

    - name: optimized_dataset_visualize
      kind: DatasetVisualize
      spec:
        key: /optimized_dataset/value
