---
apiVersion: ark.ulagbulag.io/v1alpha1
kind: Widget
metadata:
  name: remote_desktop
  labels:
    dash.ulagbulag.io/page: desktop
spec:
  actions:
    # - name: node
    #   kind: StorageRead
    #   spec:
    #     storage: k8s.io/_/nodes/v1
    #     label: 원격 제어할 노드를 선택해주세요.

    - name: session
      kind: SessionSelect
      metadata:
        column: All
      spec:
        filter: name-[bw][a-z0-9-]*
        label: 원격 제어할 노드를 선택해주세요.
        multiple: false

    - name: show_vnc
      kind: RemoteVnc
      metadata:
        column: All
      spec:
        key: /session
