---
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            cmake \
            libcairo-dev \
            libgirepository1.0-dev \
            libopenblas-dev \
            pkg-config

          python -m pip install --upgrade pip
          pip install \
            flake8 \
            pylint \
            pytest

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # stop on all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

      # FIXME: enable it when python=3.12 support
      # - name: Lint with pylint
      #   run: |
      #     python -m pylint $(git ls-files '*.py')

      - name: Test with pytest
        run: |
          python -m unittest -v tests/*.py
